version: '3.5'
services:

  sslkeygen:
      image: liip/ssl-keygen:1.0.0
      container_name: pontsun_sslkeygen
      command: ls
      environment:
          OPENSSL_CERTIFICATE_EXPIRATION: 825
          OPENSSL_CERTIFICATE_SUBJECT_COUNTRY: CH
          OPENSSL_CERTIFICATE_SUBJECT_STATE: ZH
          OPENSSL_CERTIFICATE_SUBJECT_LOCATION: Zurich
          OPENSSL_CERTIFICATE_SUBJECT_ORGANIZATION: Liip
          OPENSSL_CERTIFICATE_SUBJECT_ORGANIZATION_UNIT: Pontsun
          SITE_DOMAIN: local-vendure.com
      volumes:
          - ../.traefik/certs/:/certificates:rw
      user: $USER_ID
